name: Run Dependency Check

on: [push]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go list -json -m all > go.list

      - name: Scan dependencies with Nancy
        uses: gamertense/nancy-github-action@main
        with:
          nancyCommand: sleuth
          goListFile: go.list
          reportFile: nancy-report.txt

      - name: Upload Nancy Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: nancy-report
          path: nancy-report.txt
